### PR TITLE
Fix bug in ConfigWithDefaults get for falsey data

### LINKED ISSUE #216: Fix bug in 'ConfigWithDefaults.get'
cf https://github.com/jupyter/notebook/pull/1709, we have the same issue.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #216.

### CODE REVIEW

File: test/src/testconfig.ts [hunk 1]
```diff
@@ -177,6 +177,19 @@ describe('jupyter.services - ConfigWithDefaults', () => {
...
+    it('should get a falsey value', (done) => {
+      let handler = new RequestHandler(() => {
+        handler.respond(200, { testclass: { foo: false } });
+      });
+      let defaults: JSONObject = { foo: true };
+      let className = 'testclass';
+      getConfigSection({ name: 'test' }).then(section => {
+        let config = new ConfigWithDefaults({ section, defaults, className });
+        let data = config.get('foo');
+        expect(data).to.be(false);
```
Comment (afshin) [inline test/src/testconfig.ts]: Should this be *falsey* or outright `false`? You could use `.to.not.be.ok();' if it's the former.

Comment (blink1073) [inline test/src/testconfig.ts]: Fixed, thanks.

**Comment by afshin** [comment]
Looks good, thanks!

👍
